# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       - REDIS_URL=redis://redis:6379
#       - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
#     depends_on:
#       - mongo
#       - redis
#     command: npm run start

#   mongo:
#     image: mongo
#     ports:
#       - 3456:27017
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#       MONGO_INITDB_DATABASE: the_database
#     volumes:
#       - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
#       - mongo-data:/data/db

#   redis:
#     image: redis
#     ports:
#       - 3457:6379
#     command: ["redis-server", "--appendonly", "yes"]
#     volumes:
#       - redis-data:/data

# volumes:
#   mongo-data:
#   redis-data:
