version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend
      - todo-backend

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 5173:5173
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: todo-frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    restart: unless-stopped

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
    volumes:
      - ./todo-backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: todo-backend-dev

  mongo:
    image: mongo
    # ports:
    #   - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db

  redis:
    image: redis
    # ports:
    #   - 3457:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
