# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:80"
#     environment:
#       - VITE_BACKEND_URL=http://localhost:8080/api/
#     restart: unless-stopped
